### ISSUE TITLE
question about preparing dataset

### ISSUE THREAD

**Issue by fanW96** [feymanpriv/delf#1]
when i run the build_image_dataset.py, it inform the error " AttributeError: 'GFile' object has no attribute 'readable' ".
I have tried it on both tf2 and tf1.15, even i reinstalled my env, but nothing happened, so i came here and wanna ask if you have encountered same error or you have the solution.
thanks.

**Comment by hyu-7** [comment]
Hi, I met the same issue in running the file...May I know how you solved this?
